[2025-03-03T01:39:19.312+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_generate_data.generate_data manual__2025-03-03T01:39:13.881802+00:00 [queued]>
[2025-03-03T01:39:19.327+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_generate_data.generate_data manual__2025-03-03T01:39:13.881802+00:00 [queued]>
[2025-03-03T01:39:19.329+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-03-03T01:39:19.540+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): generate_data> on 2025-03-03 01:39:13.881802+00:00
[2025-03-03T01:39:19.552+0000] {standard_task_runner.py:57} INFO - Started process 420 to run task
[2025-03-03T01:39:19.555+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_generate_data', 'generate_data', 'manual__2025-03-03T01:39:13.881802+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline_generate_data.py', '--cfg-path', '/tmp/tmp8649aqrt']
[2025-03-03T01:39:19.557+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask generate_data
[2025-03-03T01:39:19.750+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T01:39:19.852+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_generate_data.generate_data manual__2025-03-03T01:39:13.881802+00:00 [running]> on host 93536f18dd3f
[2025-03-03T01:39:22.643+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Raffi' AIRFLOW_CTX_DAG_ID='dag_generate_data' AIRFLOW_CTX_TASK_ID='generate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T01:39:13.881802+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-03T01:39:13.881802+00:00'
[2025-03-03T01:39:26.851+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-03-03T01:39:26.887+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=dag_generate_data, task_id=generate_data, execution_date=20250303T013913, start_date=20250303T013919, end_date=20250303T013926
[2025-03-03T01:39:27.228+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-03-03T01:39:27.278+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
