[2025-03-03T06:28:04.628+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_pipeline_query.create_fact_employee manual__2025-03-03T06:22:48.623775+00:00 [None]>
[2025-03-03T06:28:04.664+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_pipeline_query.create_fact_employee manual__2025-03-03T06:22:48.623775+00:00 [None]>
[2025-03-03T06:28:04.665+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 3
[2025-03-03T06:28:04.924+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_fact_employee> on 2025-03-03 06:22:48.623775+00:00
[2025-03-03T06:28:04.982+0000] {standard_task_runner.py:57} INFO - Started process 22360 to run task
[2025-03-03T06:28:04.988+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_pipeline_query', 'create_fact_employee', 'manual__2025-03-03T06:22:48.623775+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline_query.py', '--cfg-path', '/tmp/tmpyfz7dptu']
[2025-03-03T06:28:04.992+0000] {standard_task_runner.py:85} INFO - Job 78: Subtask create_fact_employee
[2025-03-03T06:28:05.315+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T06:28:05.761+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_pipeline_query.create_fact_employee manual__2025-03-03T06:22:48.623775+00:00 [running]> on host 9b8c8285a7ac
[2025-03-03T06:28:06.597+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Raffi' AIRFLOW_CTX_DAG_ID='dag_pipeline_query' AIRFLOW_CTX_TASK_ID='create_fact_employee' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T06:22:48.623775+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-03T06:22:48.623775+00:00'
[2025-03-03T06:28:06.598+0000] {sql.py:262} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS fact_employee AS
            SELECT * FROM (select 
*
from tbl_employee te 
where te.active = 'true') AS subquery WHERE FALSE;

            TRUNCATE TABLE fact_employee;

            INSERT INTO fact_employee
            select 
*
from tbl_employee te 
where te.active = 'true';
        
[2025-03-03T06:28:06.658+0000] {base.py:73} INFO - Using connection ID 'sales_project_conn' for task execution.
[2025-03-03T06:28:06.893+0000] {base.py:73} INFO - Using connection ID 'sales_project_conn' for task execution.
[2025-03-03T06:28:06.939+0000] {sql.py:375} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS fact_employee AS
            SELECT * FROM (select 
*
from tbl_employee te 
where te.active = 'true') AS subquery WHERE FALSE;

            TRUNCATE TABLE fact_employee;

            INSERT INTO fact_employee
            select 
*
from tbl_employee te 
where te.active = 'true';
        , parameters: None
[2025-03-03T06:28:07.056+0000] {sql.py:384} INFO - Rows affected: 260
[2025-03-03T06:28:07.585+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=dag_pipeline_query, task_id=create_fact_employee, execution_date=20250303T062248, start_date=20250303T062804, end_date=20250303T062807
[2025-03-03T06:28:08.155+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-03-03T06:28:08.389+0000] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
